apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-cert-manager-core
  namespace: cert-manager
spec:
  selector: all()
  order: 100
  types:
    - Ingress
    - Egress
  ingress:
    # Allow its own pods to talk to each other
    - action: Allow
      source:
        selector: all()
  egress:
    # Allow it to talk to the Kubernetes API server and the internet
    - action: Allow