# This policy allows all pods within the flux-system to communicate freely.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-flux-system
  namespace: flux-system
spec:
  # This selects all pods in the flux-system namespace
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  # Allow all incoming and outgoing traffic to/from other pods in the same namespace
  ingress:
    - from:
      - podSelector: {}
  egress:
    - to:
      - podSelector: {}