#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#Flux-Resources
- gotk-components.yaml
- gotk-sync.yaml

#Kustomizations
- ../calico-system/operator.yaml
- ../calico-system/config.yaml
- ../metallb-system
- ../ingress-nginx
- ../network-policies/calico
