#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Bootstrap files for Flux itself
  - gotk-components.yaml
  - gotk-sync.yaml

  # Includes for our self-contained components
  - ../calico-system/calico-system.yaml
  - ../metallb-system/metallb-system.yaml
#  - ../ingress-nginx
#  - ../cert-manager

