apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calico-system         # A unique name for this step
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/base/calico-system  # The path to Calico's "playlist"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # The health check for Calico's operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tigera-operator
      namespace: tigera-operator