apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calico-config
  namespace: flux-system
spec:
  dependsOn:
    - name: calico-operator
  interval: 5m0s
  path: "./kubernetes/base/calico-system/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system