apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tigera-operator.yaml
  - custom-resources.yaml


patches:
  - path: patch-operator.yaml
    target:
      kind: Deployment
      name: tigera-operator
      namespace: tigera-operator