#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  # Includes for our self-contained components
  - calico-system
  - metallb-system
  - ingress-nginx
  - cert-manager
  - network-policies