apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC" # Change this to your timezone
          ports:
            - containerPort: 51820
              name: wireguard
              protocol: UDP
          # This is a critical security setting for a VPN
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          # This volume will store the WireGuard configuration
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wireguard-config-pvc