apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: pi-hole } }
  template:
    metadata:
      labels: { app: pi-hole }
    spec:
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - { name: WEBPASSWORD, value: {{ .Values.adminPassword | quote }} }
          # ... other env vars ...
          volumeMounts:
            - { name: pihole-config, mountPath: /etc/pihole }
      volumes:
        - name: pihole-config
          persistentVolumeClaim: { claimName: pihole-config-pvc }