apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
        - name: pihole
          image: "pihole/pihole:latest"
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 80
              name: http-web
              protocol: TCP
          env:
            - name: TZ
              value: "America/New_York" # Change to your timezone
            - name: WEBPASSWORD
              # This should be replaced by a Sealed Secret in the future
              value: "YourSecurePassword"
          volumeMounts:
            - name: pihole-config
              mountPath: /etc/pihole
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-config-pvc