apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
  namespace: pi-hole
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"