apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-svc
  namespace: pi-hole
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-svc
  namespace: pi-hole
spec:
  type: LoadBalancer
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 80