apiVersion: v1
kind: Service
metadata:
  name: pihole-web-svc
  namespace: pi-hole
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-svc
  namespace: pi-hole
spec:
  type: {{ .Values.service.dns.type }}
  ports:
    - { name: dns-tcp, port: 53, targetPort: 53, protocol: TCP }
    - { name: dns-udp, port: 53, targetPort: 53, protocol: UDP }